### ISSUE TITLE
`Op type not registered: 'RegexSplitWithOffsets'` with Tensorflow Text v1.15.1

### ISSUE THREAD

**Issue by jshph** [tensorflow/transform#170]
I'm trying to run TF Text's BertTokenizer within TF Transform's preprocessing_fn, and this is running on Kubeflow. I'm getting `RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary ...` and this looks like it resembles something that was addressed before: https://github.com/tensorflow/text/releases/tag/v1.15.0

We've verified that TF Text is installed on the Dataflow workers, so maybe that is not the issue?

Also, I ran the TF Transform component with a local beam graph and the whole graph executed successfully and wrote to local output.

I'm running TF Transform version 0.15.0, TF 1.15.2, and TF Text v1.15.1.

Any pointers would be appreciated! Thank you in advance!

**Comment by zoyahav** [comment]
How are you specifying the tf.text dependency for dataflow?

**Comment by smerdy** [comment]
@zoyahav We have a framework that allows us to write a requirements.txt file, which then generates an extra package to submit / install on Dataflow.

**Comment by zoyahav** [comment]
Would you mind sharing some more details with us such as worker logs?

**Comment by smerdy** [comment]
Yes, here's a stack trace:

```
Traceback (most recent call last):
  File "spotify_kubeflow/component/sdk/execution/run_component.py", line 62, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "spotify_kubeflow/component/sdk/execution/run_component.py", line 58, in main
    run_component(**kwargs)
  File "spotify_kubeflow/component/sdk/execution/run_component.py", line 46, in run_component
    runner.launch()
  File "/ml/spotify_kubeflow/component/sdk/execution/component_launcher.py", line 143, in launch
    execution_decision.exec_properties,
  File "/ml/spotify_kubeflow/component/sdk/execution/component_launcher.py", line 207, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/ml/spotify_kubeflow/component/common/transform/transform_executor_hparams.py", line 97, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/ml/spotify_kubeflow/component/common/transform/transform_executor_hparams.py", line 186, in Transform
    materialize_output_paths,
  File "/usr/local/lib/python3.6/dist-packages/tfx/components/transform/executor.py", line 1146, in _RunBeamImpl
    dataset.materialize_output_path))
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/pipeline.py", line 427, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1347, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 780, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 587, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 655, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 880, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/common.py", line 895, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 462, in process
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 221, in acquire
    return _shared_map.acquire(self._key, constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 184, in acquire
    result = control_block.acquire(constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 87, in acquire
    result = constructor_fn()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 462, in <lambda>
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 438, in _make_graph_state
    self._exclude_outputs, self._tf_config)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 341, in __init__
    saved_model_dir, {}))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 397, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 240, in _partially_apply_saved_transform_impl
    input_map=input_map)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on intent-classification-pip-04010736-piao-harness-ckzl. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by andrewsmartin** [comment]
Just to add some extra details on top of what @smerdy provided, we specify the tensorflow-text dependency by generating a setup.py file, generating an `sdist` and providing that through `--extra-package` (because there can sometimes be extra internal dependencies not available through public pypi). We see in the worker startup logs that this extra package is indeed installed.

**Comment by CRSilkworth** [comment]
Not sure if this is helpful but I'm encountering a similar issue with TF text-2.1.1 using tfx on kubeflow. 

Like the OP, my local beam graph with all the same components work fine works fine. Also, several of my other upstream kubeflow compontents that use TF text run without issue. These are the components being run:
```
BigQueryExampleGen - Passed
StatisticsGen - Passed
SchemaGen - Passed
ExampleValidator - Passed
Transform - Passed
Trainer - Passed
Evaluator - Failed
ModelValidator - Failed
Pusher - Not run
```
I'm using the built in 'tfx pipeline create ...' create the pipeline and docker image and these are the dependencies in my setup.py file:

```
tfx>=0.21.0,<0.22.0dev
pandas<1.0.0
httplib2<=0.12.0,>=0.8
cachetools<4, >=3.1.0
tensorflow-serving-api<2.2.0
tf-models-official==0.0.3.dev1
tensorflow-text>=2.1.0, <2.2.0
kubernetes<10.1.0
requests>=2.23.0
google-resumable-media==0.4.1
google-cloud-storage==1.22.0
kfp==0.4.0
```

Stack trace from evaluator component:
```
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 382, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 375, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/evaluator/executor.py", line 223, in Do
    slice_spec=slice_spec))
  File "/opt/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/opt/venv/lib/python3.6/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1377, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 135, in __init__
    self._construct_graph()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 169, in _construct_graph
    self._session, self._tags, self._path)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'WhitespaceTokenizeWithOffsets' in binary running on beamapp-root-0429014649-8-04281846-1j4n-harness-p4v6. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 813, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 390, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 338, in setup
    model_loader.construct_fn(self._set_model_load_seconds))
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 221, in acquire
    return _shared_map.acquire(self._key, constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 184, in acquire
    result = control_block.acquire(constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 87, in acquire
    result = constructor_fn()
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 300, in construct
    tags=tags)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 102, in __init__
    super(EvalSavedModel, self).__init__()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 138, in __init__
    general_util.reraise_augmented(exception, 'Failed to create graph.')
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/util.py", line 184, in reraise_augmented
    six.reraise(type(new_exception), new_exception, original_traceback)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 135, in __init__
    self._construct_graph()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 169, in _construct_graph
    self._session, self._tags, self._path)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'WhitespaceTokenizeWithOffsets' in binary running on beamapp-root-0429014649-8-04281846-1j4n-harness-p4v6. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. additional message: Failed to create graph.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 650, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 176, in execute
    op.start()
  File "apache_beam/runners/worker/operations.py", line 587, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 588, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 589, in apache_beam.runners.worker.operations.DoOperation.start
  File "apache_beam/runners/worker/operations.py", line 220, in apache_beam.runners.worker.operations.Operation.start
  File "apache_beam/runners/worker/operations.py", line 224, in apache_beam.runners.worker.operations.Operation.start
  File "apache_beam/runners/worker/operations.py", line 535, in apache_beam.runners.worker.operations.DoOperation.setup
  File "apache_beam/runners/worker/operations.py", line 581, in apache_beam.runners.worker.operations.DoOperation.setup
  File "apache_beam/runners/common.py", line 818, in apache_beam.runners.common.DoFnRunner.setup
  File "apache_beam/runners/common.py", line 815, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 849, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/usr/local/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 813, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 390, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 338, in setup
    model_loader.construct_fn(self._set_model_load_seconds))
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 221, in acquire
    return _shared_map.acquire(self._key, constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 184, in acquire
    result = control_block.acquire(constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 87, in acquire
    result = constructor_fn()
  File "/opt/venv/lib/python3.6/site-packages/tensorflow_model_analysis/model_util.py", line 300, in construct
    tags=tags)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 102, in __init__
    super(EvalSavedModel, self).__init__()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 138, in __init__
    general_util.reraise_augmented(exception, 'Failed to create graph.')
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/util.py", line 184, in reraise_augmented
    six.reraise(type(new_exception), new_exception, original_traceback)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 135, in __init__
    self._construct_graph()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 169, in _construct_graph
    self._session, self._tags, self._path)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'WhitespaceTokenizeWithOffsets' in binary running on beamapp-root-0429014649-8-04281846-1j4n-harness-p4v6. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. additional message: Failed to create graph. [while running 'ExtractEvaluateAndWriteResults/ExtractAndEvaluate/EvaluateMetricsAndPlots/ComputeMetricsAndPlots/ComputePerSliceMetrics/ComputeUnsampledMetrics/LoadModel']
```

If I were to guess, I would probably say it's a issue specifically when a graph with a TF text op is being loaded into DataFlow after being written to disk. Otherwise, I would have expected some of these other components (e.g. Transform, Trainer) to fail as well.

**Comment by jshph** [comment]
@CRSilkworth thanks, that's an interesting lead... your other components that make use of TF Text don't make use of TF Text ops at all? What version of Tensorflow are you using?

**Comment by CRSilkworth** [comment]
@jshph tfx==0.21 uses tensorflow==2.1.0.

I'm don't think I understand what you're asking. Are you asking which of the components use TF text?  The first four (BigQueryExampleGen,  StatisticsGen, SchemaGen and ExampleValidator) don't explicitly use TF text. Actually now that I think about it, my Transform component doesn't use it either. Only from the Trainer component onward does a TF text op become a part of the graph. The Trainer component (tf estimator-based) works fine. It's only after the graph has been written to disk and reloaded in another component to be used again that the TF text op fails to get registered.

**Comment by zoyahav** [comment]
A recent change to tf.Transform should resolve the issue of using tf.text ops in the Transform preprocessing_fn: https://github.com/tensorflow/transform/commit/7ec6244fffbcce76e38f0a59472f3a0b282e34ef

If you could change the tf.Transform version that you're using (in the 1st comment), then this change would be available when installing the next TFT version (0.23) or through either:
 - installing a recent TFT nightly build (pip install -i https://test.pypi.org/simple/ tensorflow-transform --pre)
 - installing TFT from github master (pip install git+https://github.com/tensorflow/transform.git)

Note that this is for the original issue in Transform, the issue described above with ModelValidator should also be resolved.

**Comment by zoyahav** [comment]
Closing this issue as it's been fixed at head (currently available on nightly) and will be included in our next release.
Please let us know if you encounter further issues with these fixes.

Btw, a similar fix was recently added to ModelValidator as well: https://github.com/tensorflow/model-analysis/commit/5b393f4d5b64db65d338591bd4470870d400e6a8

**Comment by CRSilkworth** [comment]
It looks like this is still an issue for the Evaluator component. The tf text ops are not getting registered after reload if the text ops are defined in the trainer component. I'm running with:
tfx==0.23.1
tensorflow==2.3.1
tensorflow-text==2.3.0

As before, it runs fine when using beam as an orchestrator but with kubeflow it fails. 
```
  File "apache_beam/runners/common.py", line 1253, in apache_beam.runners.common.DoFnRunner._invoke_lifecycle_method
  File "apache_beam/runners/common.py", line 504, in apache_beam.runners.common.DoFnInvoker.invoke_setup
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator_v2.py", line 226, in setup
    computation.preprocessor.setup()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/model_util.py", line 375, in setup
    model_load_time_callback=self._set_model_load_seconds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/types.py", line 155, in load
    return self._shared_handle.acquire(construct_fn)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 242, in acquire
    return _shared_map.acquire(self._key, constructor_fn, tag)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 198, in acquire
    result = control_block.acquire(constructor_fn, tag)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 93, in acquire
    result = constructor_fn()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/types.py", line 164, in with_load_times
    model = self.construct_fn()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_model_analysis/model_util.py", line 335, in construct_fn
    tags=tags)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 102, in __init__
    super(EvalSavedModel, self).__init__()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 138, in __init__
    general_util.reraise_augmented(exception, 'Failed to create graph.')
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/util.py", line 184, in reraise_augmented
    six.reraise(type(new_exception), new_exception, original_traceback)
  File "/usr/local/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/eval_metrics_graph/eval_metrics_graph.py", line 135, in __init__
    self._construct_graph()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/eval_saved_model/load.py", line 169, in _construct_graph
    self._session, self._tags, self._path)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 299, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 452, in load
    **saver_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 382, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1486, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/meta_graph.py", line 799, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'WhitespaceTokenizeWithOffsets' in binary running on beamapp-root-1210090848-0-12100108-l9hc-harness-tpn2. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. additional message: Failed to create graph.```

**Comment by CRSilkworth** [comment]
This also appears only to be an issue when running using DataFlow. Using DirectRunner, it passes without issue even using kubeflow orchestration.

**Comment by cloudy-sfu** [comment]
Install tensorflow-text
`pip install tensorflow-text --no-dependencies`
